### ISSUE TITLE
how to change the language

### ISSUE THREAD

**Issue by felipepxavier** [zackify/react-calendar#10]
Hi! first congratulations for the project!
Friend, how can I change the calendar language?

I saw now that the recommended thing would be to edit the package, thanks!

**Comment by zackify** [comment]
You can pass in a locale prop: https://github.com/zackify/react-calendar/pull/6/files#diff-0a2cba436167c0c5c597baa72a93168dd90435d7603a6b408d7b75c618d7ecc3R47

does this solve the problem?
