### ISSUE TITLE
Large Bundle Size

### ISSUE THREAD

**Issue by eruby-br** [zackify/react-calendar#11]
I use an import-cost extension in vs code in an effort to absolutely minimize my bundle size.
This library interested me since I have used react-big-calendar for some time, but would consider moving to a newer code base, however the basic example in your documentation clocks in at 500+k unzipped, whereas react-big-calendar is 124k unzipped. While react-big-calendar is still on the hefty side, it's much closer to an ideal size.

I am not really sure where you might be able to optimize this, but I don't think I'm the only person who might be deterred from using this for this reason.

If you're able to get the size down I'd be happy to try it out on a production site.

**Comment by zackify** [comment]
https://bundlephobia.com/package/@zach.codes/react-calendar

The library itself is incredibly small. It’s only 6kb minified. 

The rest of the size is date-fns and React, which I can’t get rid of. I would say many apps use date-fns so it might already be in use. 

Date-fns is 88kb minified https://bundlephobia.com/package/date-fns

React is 7kb minified 
https://bundlephobia.com/package/react

react-dom is 121kb https://bundlephobia.com/package/react-dom

**Comment by zackify** [comment]
If you don’t believe my numbers, you can look at the package.json and see that there are no other dependencies. So I’m not sure how you’re seeing it so large.
