### ISSUE TITLE
Add ability for consumers to set some styles

### ISSUE THREAD

**Issue by smai-f** [zackify/react-calendar#12]
Hey, this project is very swell, thank you so much!

I'd love to be able to customize the styles within `MonthlyNav` to [change the flex spacing](https://github.com/zackify/react-calendar/blob/master/src/Monthly/MonthlyCalendar.tsx#L62) as well as the next/previous buttons & month title.

I can wrap your component with a div and do some custom selecting and !importanting to make it work, but I'd prefer not to if possible. Am I missing another way to do this?

Do you have an API in mind for the future to allow consumers to set custom styles as in this case? Or perhaps by adding and exporting custom class names to some elements to allow the consumer to style them?

**Comment by smai-f** [comment]
Related! https://github.com/zackify/react-calendar/issues/8

**Comment by zackify** [comment]
This is the same answer as #8, in this case, MonthlyNav is also a very simple default. The solution is to make your own, inside your app: 

```js
export const MonthlyNav = () => {
  let { locale, currentMonth, onCurrentMonthChange } = useMonthlyCalendar();

  return (
    <div className="rc-flex rc-justify-end rc-mb-4">
      <button
        onClick={() => onCurrentMonthChange(subMonths(currentMonth, 1))}
        className="rc-cursor-pointer"
      >
        Previous
      </button>
      <div
        className="rc-ml-4 rc-mr-4 rc-w-32 rc-text-center"
        aria-label="Current Month"
      >
        {format(
          currentMonth,
          getYear(currentMonth) === getYear(new Date()) ? 'LLLL' : 'LLLL yyyy',
          { locale }
        )}
      </div>
      <button
        onClick={() => onCurrentMonthChange(addMonths(currentMonth, 1))}
        className="rc-cursor-pointer"
      >
        Next
      </button>
    </div>
  );
};
```
`useMonthlyCalendar` is exported from the library and you are welcome to fully control everything with your own version of this component :)

**Comment by smai-f** [comment]
Thank you @zackify , much appreciated!
