### ISSUE TITLE
Can't resolve 'date-fns/locale'

### ISSUE THREAD

**Issue by gustavazo** [zackify/react-calendar#16]
I tried to install this library in two different environments and I get the same error:

Can't resolve 'date-fns/locale' in 'C:\Users\intot\Documents\GitHub\Nueva carpeta\gym-admin\node_modules\@zach.codes\react-calendar\dist'

I tried to install date-fns manually and I get the same problem.

I'm using latest version.

**Comment by zackify** [comment]
date-fns should be installed by you, alongside this library. 

It sounds like it’s missing, but you said you installed it. 

Can you confirm that it exists inside node_modules/date-fns?

**Comment by gustavazo** [comment]
Yes. It's installed. I will create a project from scratch and see if it works.

**Comment by gustavazo** [comment]
Was a problem with a local environemnt.
