### ISSUE TITLE
WeeklyDays locale es

### ISSUE THREAD

**Issue by AlexCernik** [zackify/react-calendar#17]
I have a problem with calendar weekly and { locale: es }.

<WeeklyCalendar locale={es} week={new Date()}>

![2](https://user-images.githubusercontent.com/57844660/127272337-bdd38ebc-4a92-4d07-bf32-471d57ac1df2.png)

and without  { locale: es }  is correct render, 

![3](https://user-images.githubusercontent.com/57844660/127272517-8594e412-d609-48b1-83cb-1eb6c67ff741.png)

**Comment by zackify** [comment]
What is wrong with the rendering? I don't see an issue

**Comment by AlexCernik** [comment]
> What is wrong with the rendering? I don't see an issue

The rendering of the week is wrong when Local is changed to another language

**Comment by zackify** [comment]
is it the day numbers being incorrect?

**Comment by AlexCernik** [comment]
> is it the day numbers being incorrect?

yes, the change the locale to another language do not select the current week
