### ISSUE TITLE
MonthlyBody doesn't render days in the calendar

### ISSUE THREAD

**Issue by jzeng808** [zackify/react-calendar#19]
I am using the basic monthly calendar in my Next.js project (Node Version: 14.15.4). The "Day of Week" and "Empty Day" are generated but the actual days are not being displayed. 

<MonthlyCalendar 
            currentMonth={currentMonth}
            onCurrentMonthChange={date => setCurrentMonth(date)}>
                <MonthlyNav />
                <MonthlyBody
                    //omitDays={[0, 6]}
                    events={[
                        { title: 'Call Jane', date: subHours(new Date(), 2) },
                        { title: 'Call John', date: subHours(new Date(), 1) },
                        { title: 'Meeting with Bob', date: new Date() }
                    ]}           
                    renderDay={data =>
                        data.map((item, index) => (
                        <DefaultMonthlyEventItem
                            key={index}
                            title={item.title}
                            date={format(item.date, 'k:mm')}
                        />
                        ))
                    }     
                    />              
        </MonthlyCalendar>

**Comment by nategabriel** [comment]
You're missing `<MonthlyDay>`. The sample code is omitting that but its included in the Basic Usage section of the readme file.

`<MonthlyCalendar
  currentMonth={currentMonth}
  onCurrentMonthChange={date => setCurrentMonth(date)}
>
  <MonthlyNav />
  <MonthlyBody
    events={[
      {
        date: new Date('2022-09-01T15:56:15.560Z'),
        title: 'Call John'
      },
      {
        date: new Date('2022-09-01T16:56:15.560Z'),
        title: 'Call John'
      },
      {
        date: new Date('2022-09-01T17:56:15.560Z'),
        title: 'Meeting with Bob'
      }
    ]}
    renderDay={function noRefCheck(){}}
  >
    <MonthlyDay
      renderDay={data =>
        data.map((item, index) => (
          <DefaultMonthlyEventItem
            key={index}
            title={item.title}
            // Format the date here to be in the format you prefer
            date={format(item.date, 'k:mm')}
          />
        ))
      }
    />
  </MonthlyBody>
</MonthlyCalendar>`

**Comment by zackify** [comment]
Thank you!
