### ISSUE TITLE
Empty Day is not a matching aria-label; use article instead

### ISSUE THREAD

**Issue by danielmilano1** [zackify/react-calendar#21]
If you're looking for possible ARIA roles that could be relevant in representing the concept of an "empty day" within a web application or interface, here's a role that you could consider:

"article": The article role can be used to mark a section of content that is considered independent and self-contained. In the context of an "empty day," you can consider marking the entire day as an "article" to indicate that it is a distinct unit with no specific tasks or events. This role is more suitable when you have a container representing the day, and you want to mark it as an empty entity.

**Comment by zackify** [comment]
Good idea, mind submitting a pr?

**Comment by danielmilano1** [comment]
Sure thing!

**Comment by danielmilano1** [comment]
https://github.com/zackify/react-calendar/pull/22

**Comment by zackify** [comment]
https://github.com/zackify/react-calendar/releases/tag/0.3.2
