### ISSUE TITLE
calendar.zach.codes not resolving DNS

### ISSUE THREAD

**Issue by lyndonbuckley** [zackify/react-calendar#25]
hey @zackify,

Just a heads up this domain isn't resolving currently

![Screenshot 2023-12-12 at 2 28 19 pm](https://github.com/zackify/react-calendar/assets/3122733/1817a22a-f8c5-4368-a91c-1f3530bc83d8)

**Comment by jsaunders92** [comment]
I also wonder, is this still being maintained?

**Comment by zackify** [comment]
sorry guys, just dont have much time to devote to my open source projects but ill do the best i can if you have anything to add to this.

The library is still pretty simple and usable even after a few years have passed.

i fixed the url to just use the default one if you want to see the stories: https://zackify.github.io/react-calendar

**Comment by jsaunders92** [comment]
Completely understand. Thank you for fixing the URL, that's useful!
