### ISSUE TITLE
Allow locale customization

### ISSUE THREAD

**Issue by Ramiracle** [zackify/react-calendar#5]
I don't seem to find a way to select my locale. If a use a custom component i can: 

`{format(
      currentMonth,
      getYear(currentMonth) === getYear(new Date())
          ? "LLLL"
          : "LLLL yyyy",
          { locale: es }
  )}`
  
  But if want to show days name in spanish in monthly calendar table I can't.

**Comment by zackify** [comment]
Good idea, I will add a locale prop to the top level component, and then all of them will take it from the context. Should be able to do it in a couple days

**Comment by zackify** [comment]
sorry, i forgot about this, please try out this version
```
npm install @zach.codes/react-calendar@0.2.0-beta
```

if it looks good i can release it. I already added a couple basic tests. Pass the locale to the root component

**Comment by zackify** [comment]
Published it publicly in 0.2.0
