### ISSUE TITLE
Customizable days of week

### ISSUE THREAD

**Issue by paquirus** [zackify/react-calendar#7]
It would be interesting to allow customize the days of week.
For example: change from "Sunday, Monday...." to "Domingo, Lunes...." or "dimanche, Lundi..."

I don't really know if it is possible on this release.

![image](https://user-images.githubusercontent.com/42079503/119742497-cce7f180-be3c-11eb-9478-c2d5778a2ffb.png)

**Comment by zackify** [comment]
Have you tried using this pr and changing the locale? https://github.com/zackify/react-calendar/issues/5

**Comment by paquirus** [comment]
Yeah. Im using the locale prop with "es" value. Let me show you some examples about this case.

When the calendar component size is "lg" (or laptop screen size), the locale prop works with the month into Nav component. check it out
![image](https://user-images.githubusercontent.com/42079503/119868262-acb74180-bed3-11eb-8dc7-40b31b77a400.png)

here the code
![image](https://user-images.githubusercontent.com/42079503/119868473-ec7e2900-bed3-11eb-8a8c-1bfab8746d42.png)

But, when i apply zoom (175%) in google chrome, the calendar changed to mobile or tablet size (i don't know, but it is nice), the locale is applied. Check it out
![image](https://user-images.githubusercontent.com/42079503/119870138-df623980-bed5-11eb-92ff-569130924cc7.png)

**Comment by zackify** [comment]
Thanks for the info! I must have missed passing in the locale to one place on the desktop view. I will fix and release today

**Comment by zackify** [comment]
Please install `0.2.0-beta2` I have fixed the week day names and added a test to make sure

**Comment by paquirus** [comment]
Fixed
